version: 2
updates:
  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Python package updates
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
