# See https://pre-commit.com for more information
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: debug-statements
    -   id: check-ast
    -   id: check-builtin-literals
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: detect-private-key
    -   id: mixed-line-ending
    -   id: requirements-txt-fixer

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
    -   id: ruff-check
        args: [--fix, --exit-non-zero-on-fix]
    -   id: ruff-format

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
    -   id: mypy
        additional_dependencies: [pydantic>=2.0, httpx>=0.25, types-requests]
        args: [--strict, --ignore-missing-imports]
        files: ^src/

-   repo: https://github.com/PyCQA/bandit
    rev: '1.8.6'
    hooks:
    -   id: bandit
        args: [-r, src/]
        exclude: tests/

-   repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.34.0
    hooks:
    -   id: check-github-workflows
    -   id: check-dependabot

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: python-use-type-annotations
    -   id: python-check-blanket-noqa
    -   id: python-check-blanket-type-ignore
    -   id: rst-backticks
    -   id: rst-directive-colons

-   repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
    -   id: codespell
        args: [--write-changes]
        exclude: ^(uv\.lock|\.git/)

-   repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.10.0
    hooks:
    -   id: pyproject-fmt
        additional_dependencies: [tox]

default_language_version:
    python: python3

ci:
    autofix_commit_msg: 'style: auto fixes from pre-commit hooks'
    autofix_prs: true
    autoupdate_commit_msg: 'ci: pre-commit autoupdate'
    autoupdate_schedule: weekly
