"""Python client for the Ökobox Online REST API."""

from .client import OekoboxClient
from .exceptions import (
    OekoboxAPIError,
    OekoboxAuthenticationError,
    OekoboxConnectionError,
    OekoboxError,
    OekoboxValidationError,
)
from .models import (
    Address,
    Article,
    Box,
    CartItem,
    CustomerInfo,
    DDate,
    Delivery,
    DeliveryState,
    Discount,
    Favourite,
    Group,
    Item,
    Navigation,
    Order,
    Position,
    Shop,
    SubGroup,
    Subscription,
    Tour,
    UserInfo,
    Voucher,
    XUnit,
)

__version__ = "0.1.0"
__all__ = [
    "Address",
    "Article",
    "Box",
    "CartItem",
    "CustomerInfo",
    "DDate",
    "Delivery",
    "DeliveryState",
    "Discount",
    "Favourite",
    "Group",
    "Item",
    "Navigation",
    "OekoboxAPIError",
    "OekoboxAuthenticationError",
    "OekoboxClient",
    "OekoboxConnectionError",
    "OekoboxError",
    "OekoboxValidationError",
    "Order",
    "Position",
    "Shop",
    "SubGroup",
    "Subscription",
    "Tour",
    "UserInfo",
    "Voucher",
    "XUnit",
]
